import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const generatedAt = process.env.GROWTH_KIT_DATE || new Date().toISOString().slice(0, 10);
const repoUrl = 'https://github.com/chenyuan35/aineedhelpfromotherai';
const siteUrl = 'https://aineedhelpfromotherai.com';
const apiUrl = 'https://api.aineedhelpfromotherai.com';
const fence = '```';

function readJson(path) {
  return JSON.parse(readFileSync(join(root, path), 'utf8'));
}

function minutesFor(c) {
  return Number(c.time_wasted_minutes || c.time_lost_min || 0);
}

function write(path, body) {
  const file = join(root, path);
  mkdirSync(dirname(file), { recursive: true });
  const content = `${body.trimEnd()}\n`;
  if (existsSync(file) && readFileSync(file, 'utf8') === content) {
    console.log(`unchanged ${path}`);
    return;
  }
  writeFileSync(file, content);
  console.log(`wrote ${path}`);
}

function firstLine(value, fallback = '') {
  const text = String(value || fallback).replace(/\s+/g, ' ').trim();
  return text.length > 180 ? `${text.slice(0, 177)}...` : text;
}

const allCases = readJson('data/failure-cases.json');
const cases = allCases.filter(c => c?.source !== 'daily-auto-generate' && !String(c?.id || '').startsWith('FC_AUTO_'));
const dynamics = readJson('data/failure-dynamics.json');
const sitemap = readFileSync(join(root, 'frontend', 'sitemap.xml'), 'utf8');
const sitemapUrls = Array.from(sitemap.matchAll(/<loc>(.*?)<\/loc>/g), m => m[1]);
const totalMinutes = cases.reduce((sum, c) => sum + minutesFor(c), 0);
const totalHours = Math.round(totalMinutes / 60);
const interventions = dynamics.flatMap(d => d.interventions || []);
const pendingInterventions = interventions.filter(i => i.effectiveness_tracking === 'pending').length;
const topCases = [...cases].sort((a, b) => minutesFor(b) - minutesFor(a)).slice(0, 5);
const topDynamics = [...dynamics].sort((a, b) => b.total_time_wasted_min - a.total_time_wasted_min);

const evidenceLine = `${cases.length} failure cases, ${totalMinutes.toLocaleString()} wasted minutes (${totalHours} hours), ${dynamics.length} failure dynamics, ${interventions.length} interventions`;
const topCaseLines = topCases.map(c => `- ${c.id}: ${c.title} (${minutesFor(c).toLocaleString()} min)`);
const dynamicsLines = topDynamics.map(d => `- ${d.name}: ${d.total_cases} cases, ${Number(d.total_time_wasted_min).toLocaleString()} wasted minutes, trigger: ${firstLine(d.indicator)}`);

write('BETA-RECRUIT.md', [
  '# Failure Memory - beta recruiting kit',
  '',
  `Generated: ${generatedAt}`,
  '',
  '## What it is',
  '',
  'A shared failure memory for AI coding agents. It helps agents search known debugging failures before they retry the same wrong fix.',
  '',
  '## Evidence',
  '',
  `- ${evidenceLine}`,
  `- ${pendingInterventions} interventions still need measured effectiveness data`,
  `- ${sitemapUrls.length} public URLs in the sitemap`,
  '',
  'Top observed failures:',
  '',
  ...topCaseLines,
  '',
  'Top failure dynamics:',
  '',
  ...dynamicsLines,
  '',
  '## The hook',
  '',
  'Your agent should check the shared failure memory before it burns another debugging hour.',
  '',
  '## The 3-call loop',
  '',
  '1. Before fixing: POST /api/memory/search to find similar failures.',
  '2. When stuck: POST /api/memory/failure to record the failed path.',
  '3. After verification: POST /api/memory/resolution to save the fix as reusable evidence.',
  '',
  'MCP clients can use the same workflow through resolve_reasoning and check_failures.',
  '',
  '## Try it',
  '',
  fence + 'bash',
  `curl -s -X POST "${apiUrl}/api/memory/search" \\`,
  '  -H "Content-Type: application/json" \\',
  '  -d \'{"query":"Claude Code hallucinated CLI flag","limit":3}\'',
  fence,
  '',
  '## Target users',
  '',
  '| Role | Why this is a fit | First ask |',
  '|------|-------------------|-----------|',
  '| Claude Code daily user | Feels session drift and repeated tool failures | Ask for one recent repeated debugging loop |',
  '| Cursor power user | Hits context limits and retry loops | Ask for a case where a fresh session lost context |',
  '| MCP tool builder | Can integrate memory at tool-call boundary | Ask which MCP response shape is easiest |',
  '| Open source maintainer | Sees repeated issue triage by different agents | Ask which failure pattern recurs in their repo |',
  '| AI infra engineer | Owns agent reliability and evaluation loops | Ask what evidence would make a memory trustworthy |',
  '',
  '## Short DM / email',
  '',
  'Subject: Can your coding agent reuse other agents failed debugging attempts?',
  '',
  'Hey [name], quick ask.',
  '',
  `I am testing Failure Memory: ${evidenceLine}. The narrow problem is repeated AI debugging waste: an agent locks onto a wrong root cause, retries, and every fresh session starts from zero.`,
  '',
  'The loop is tiny: search memory before fixing, record failed paths when stuck, store the verified fix after the test passes.',
  '',
  `Try the search API: ${apiUrl}/api/memory/search`,
  '',
  'I am looking for beta users who can bring one real recent agent failure and tell me whether the returned memory would have changed the next action.',
  '',
  'Worth a look?',
  '',
  '## What beta users get',
  '',
  '1. Help wiring MCP, curl, bash, or custom tool integration.',
  '2. Public failure cases they can inspect before trusting the system.',
  '3. A direct path to add their own observed failures.',
  '4. No auth requirement for the public beta API.',
  '',
  '## What we need back',
  '',
  '1. One real repeated debugging failure.',
  '2. Whether search changed the next action.',
  '3. What verification evidence made the memory usable or unusable.',
  '',
  '## Contact',
  '',
  `- Site: ${siteUrl}`,
  `- Cases: ${siteUrl}/cases/`,
  `- API docs: ${siteUrl}/api/docs/`,
  `- Repo: ${repoUrl}`,
].join('\n'));

write('tasks/show-hn-draft.md', [
  '# Show HN draft',
  '',
  'Title: Show HN: Failure Memory for AI coding agents',
  '',
  'First three lines:',
  '',
  `I built a small failure memory for AI coding agents: ${siteUrl}`,
  `It is based on ${cases.length} observed debugging failures totaling ${totalMinutes.toLocaleString()} wasted minutes.`,
  'The narrow question is: can an agent avoid a repeated debugging loop if it searches prior failures before changing code?',
  '',
  'Post:',
  '',
  'Most agent memory demos focus on preferences or long-term project context. I wanted something narrower and easier to falsify: debugging failures that wasted time, the wrong assumption that caused them, and the fastest check that would have stopped the loop.',
  '',
  `The current dataset has ${cases.length} failure cases, ${dynamics.length} clustered failure dynamics, and ${interventions.length} proposed interventions. The intervention counts are intentionally still marked pending until they save measured minutes in real sessions.`,
  '',
  'Examples:',
  '',
  ...topCaseLines,
  '',
  'The site now exposes three practical surfaces:',
  '',
  `- Case library: ${siteUrl}/cases/`,
  `- MCP/API docs: ${siteUrl}/api/docs/`,
  `- Live stats: ${siteUrl}/stats/`,
  '',
  'The API loop is intentionally small:',
  '',
  '1. Search memory before debugging from scratch.',
  '2. Check known failure risks before applying a plausible fix.',
  '3. Store only fixes with verification evidence.',
  '',
  'The goal is not an agent marketplace, benchmark leaderboard, or general autonomous platform. It is a measurement question: which interventions reduce AI debugging time waste?',
  '',
  'What I would like feedback on:',
  '',
  '- Is the failure case format specific enough to change an agent action?',
  '- What evidence would make you trust or reject a shared memory entry?',
  '- Which integration surface is least annoying: MCP, REST, shell wrapper, or repo-local file?',
  '',
  `Repo: ${repoUrl}`,
].join('\n'));

write('docs-posts/devto-article.md', [
  '---',
  'title: "I Built a Failure Memory for AI Coding Agents"',
  'published: false',
  'tags: mcp, ai, debugging, opensource',
  'description: "A small MCP and REST memory loop built from real AI debugging failures, root causes, and interventions."',
  '---',
  '',
  '## TL;DR',
  '',
  `I built Failure Memory for AI coding agents: ${siteUrl}`,
  '',
  `It currently tracks ${cases.length} observed debugging failures, ${totalMinutes.toLocaleString()} wasted minutes, ${dynamics.length} recurring failure dynamics, and ${interventions.length} interventions that still need measured effectiveness data.`,
  '',
  'The idea is simple: before an agent retries a plausible fix, it should search prior failures and check whether another agent already wasted time on the same wrong assumption.',
  '',
  '## The problem',
  '',
  'AI coding agents often fail in recognizable ways:',
  '',
  '- They lock onto the first plausible root cause.',
  '- They retry the same command with tiny variations.',
  '- They declare success without running verification.',
  '- They debug against an imagined environment instead of the real runtime.',
  '- They lose the original problem shape across long sessions.',
  '',
  'These are not abstract concerns. They show up as real minutes lost.',
  '',
  '## Current evidence',
  '',
  ...dynamicsLines,
  '',
  'The case library includes failures like:',
  '',
  ...topCaseLines,
  '',
  '## The product surface',
  '',
  'Failure Memory exposes a narrow loop:',
  '',
  '1. Search memory before debugging from scratch.',
  '2. Check known failure risks before applying a fix.',
  '3. Store verified fixes with evidence after the test passes.',
  '',
  'REST example:',
  '',
  fence + 'bash',
  `curl -s -X POST "${apiUrl}/api/memory/search" \\`,
  '  -H "Content-Type: application/json" \\',
  '  -d \'{"query":"npm install retry spiral ECONNRESET","limit":3}\'',
  fence,
  '',
  'MCP clients can use the same idea through the public MCP endpoint:',
  '',
  fence + 'json',
  '{',
  '  "mcpServers": {',
  '    "aineedhelpfromotherai": {',
  `      "url": "${apiUrl}/mcp",`,
  '      "type": "streamable-http"',
  '    }',
  '  }',
  '}',
  fence,
  '',
  '## What changed on the site',
  '',
  'The public frontend now focuses on the actual research question instead of a broad agent platform:',
  '',
  `- ${siteUrl}/cases/ shows the case library and intervention map.`,
  `- ${siteUrl}/stats/ shows live memory and activity stats.`,
  `- ${siteUrl}/api/docs/ gives the integration surface.`,
  '',
  '## What I want to learn next',
  '',
  'The open question is not whether agents should have more memory. It is which specific memory checks reduce debugging time waste.',
  '',
  'If you use Claude Code, Cursor, Windsurf, OpenCode, Codex-style agents, or an MCP-compatible coding runtime, I am looking for beta users who can bring one real recent failure and test whether the memory changes the next action.',
  '',
  `GitHub: ${repoUrl}`,
].join('\n'));

write('tasks/growth-posts.md', [
  '# Growth posts - high-intent only',
  '',
  `Generated: ${generatedAt}`,
  '',
  'These are targeted outreach drafts. Use them where the thread is already about AI coding-agent debugging waste, repeated failures, MCP memory, or agent verification. Do not mass-post identical text.',
  '',
  '## One-line positioning',
  '',
  'Failure Memory helps AI coding agents search prior debugging failures before repeating the same wrong fix.',
  '',
  '## Short social post',
  '',
  `I rebuilt aineedhelpfromotherai around one measurable question: what interventions reduce AI debugging time waste? Current data: ${evidenceLine}. The case library now includes an intervention map, live stats, and a tiny MCP/REST loop for searching failures before an agent retries. ${siteUrl}/cases/`,
  '',
  '## Reddit / forum post',
  '',
  'Title: I am testing whether shared failure memory can stop AI coding agents from repeating debugging loops',
  '',
  `I have been collecting real AI debugging failures and clustering them by mechanism. Current dataset: ${cases.length} cases, ${totalMinutes.toLocaleString()} wasted minutes, ${dynamics.length} dynamics, ${interventions.length} interventions.`,
  '',
  'The most common patterns are false root-cause lock, retry spirals, verification collapse, environment blindness, and context drift.',
  '',
  'The project is intentionally narrow: before an agent changes code, it can search known failures and check whether the proposed path looks like a known trap.',
  '',
  `Case library: ${siteUrl}/cases/`,
  `API docs: ${siteUrl}/api/docs/`,
  '',
  'Question for people using coding agents daily: what recent failure would you want this memory layer to catch before the agent acted?',
  '',
  '## GitHub issue update',
  '',
  'Title: Beta update - intervention map and API examples now match the current site',
  '',
  `The beta surface now has ${cases.length} cases and an intervention map built from ${dynamics.length} dynamics: ${siteUrl}/cases/`,
  '',
  'The live site and docs now point to the working /api/memory/search route, and the case pages show the trigger and guardrail that should stop an agent before it retries.',
  '',
  'Good beta feedback now means one real recent failure plus an answer to: did search memory change the next action?',
  '',
  '## Directory submission',
  '',
  'Name: Failure Memory',
  '',
  'One-liner: Shared MCP and REST failure memory that helps AI coding agents search known debugging traps before retrying.',
  '',
  `Description: Failure Memory is a public MCP/REST service built from ${cases.length} observed AI debugging failures. It clusters failures into ${dynamics.length} dynamics and exposes a small loop: search memory before debugging, check failure risks before acting, and store verified fixes with evidence.`,
].join('\n'));

write('tasks/directory-submission.md', [
  '# Directory submission - Failure Memory',
  '',
  '## Name',
  '',
  'Failure Memory',
  '',
  '## One-liner',
  '',
  'Shared MCP and REST failure memory that helps AI coding agents search known debugging traps before retrying.',
  '',
  '## Category',
  '',
  'MCP Server / AI Agent Debugging / Developer Tool',
  '',
  '## Description',
  '',
  `Failure Memory is a public MCP and REST service built from ${cases.length} observed AI debugging failures totaling ${totalMinutes.toLocaleString()} wasted minutes. It clusters failures into ${dynamics.length} recurring dynamics and exposes a narrow loop for agents: search memory before debugging, check known failure risks before acting, and store verified fixes with evidence.`,
  '',
  '## Current evidence',
  '',
  ...dynamicsLines,
  '',
  '## Integration',
  '',
  `- Site: ${siteUrl}`,
  `- Case library: ${siteUrl}/cases/`,
  `- API docs: ${siteUrl}/api/docs/`,
  `- MCP endpoint: POST ${apiUrl}/mcp`,
  `- REST search: POST ${apiUrl}/api/memory/search`,
  '',
  '## Tags',
  '',
  'mcp-server, ai-agents, debugging, failure-analysis, agent-memory, developer-tools',
].join('\n'));

write('tasks/awesome-mcp-servers-pr.md', [
  '# awesome-mcp-servers PR proposal',
  '',
  '## Suggested README entry',
  '',
  '### Failure Memory',
  '',
  `Shared MCP and REST failure memory for AI coding agents. It is built from ${cases.length} observed debugging failures totaling ${totalMinutes.toLocaleString()} wasted minutes, clustered into ${dynamics.length} failure dynamics with ${interventions.length} interventions to test.`,
  '',
  'Agents use it to search known failures before debugging from scratch, check risky approaches before acting, and store verified fixes after tests pass.',
  '',
  `- Website: ${siteUrl}`,
  `- Cases: ${siteUrl}/cases/`,
  `- API docs: ${siteUrl}/api/docs/`,
  `- MCP endpoint: ${apiUrl}/mcp`,
  `- Repository: ${repoUrl}`,
  '',
  '## Why this fits',
  '',
  '- It is a working public MCP endpoint, not only a library.',
  '- The scope is narrow: reduce repeated AI debugging waste.',
  '- The data is inspectable through public case pages.',
  '- The integration path supports both MCP clients and direct REST calls.',
].join('\n'));

write('tasks/github-beta-update.md', [
  '## Beta update - intervention map and working API examples',
  '',
  `The beta surface now has ${cases.length} failure cases and an intervention map built from ${dynamics.length} measured dynamics: ${siteUrl}/cases/`,
  '',
  `The dataset currently totals ${totalMinutes.toLocaleString()} wasted debugging minutes and tracks ${interventions.length} interventions. The intervention rows are intentionally still marked pending until they save measured minutes in real sessions.`,
  '',
  'What changed:',
  '',
  `- public case library and intervention map: ${siteUrl}/cases/`,
  `- live stats/trust surface: ${siteUrl}/stats/`,
  `- working REST memory route in examples: ${apiUrl}/api/memory/search`,
  `- API docs: ${siteUrl}/api/docs/`,
  '',
  'Best beta feedback now: bring one real recent AI-agent debugging failure and test whether search memory changes the next action before the agent edits code.',
].join('\n'));

console.log(`growth kit ready: ${evidenceLine}`);
